### ISSUE TITLE
Troubles

### ISSUE THREAD

**Issue by eshimischi** [wonderful-panda/vue-typed-component#1]
Hi, thanks for your projects (and vue-tsx-support especially), but when i tried this component, i got a mistakes like:

`Hash: 31d7833a0d0767ba0806
Version: webpack 2.7.0
Time: 2070ms
       Asset     Size  Chunks             Chunk Names
    index.js  29.9 kB       0  [emitted]  main
index.js.map  31.7 kB       0  [emitted]  main
   [1] ./props.ts 7.9 kB {0} [built] [33 errors]
   [2] ../~/vue-class-component/dist/vue-class-component.common.js 4.2 kB {0} [built]
   [4] ../~/process/browser.js 5.42 kB {0} [built]
   [5] ./index.ts 5.6 kB {0} [built] [10 errors]
    + 2 hidden modules

ERROR in /Users/eshi/vue-typed-component/node_modules/vue-class-component/lib/declarations.d.ts
(6,33): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(9,37): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(10,37): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(18,91): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(19,34): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(21,54): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(31,31): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(32,30): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(44,29): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(45,32): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(46,30): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(47,33): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(48,41): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(49,17): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(50,18): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(51,21): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(70,30): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(71,18): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(72,38): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./props.ts
(9,37): error TS4081: Exported type alias 'PropOrValidator' has or is using private name 'Vue'.

ERROR in ./props.ts
(10,37): error TS4081: Exported type alias 'PropOrValidator' has or is using private name 'Vue'.

ERROR in ./props.ts
(31,31): error TS4057: Return type of method from exported interface has or is using private name 'Vue'.

ERROR in ./props.ts
(32,30): error TS4057: Return type of method from exported interface has or is using private name 'Vue'.

ERROR in ./props.ts
(44,29): error TS4057: Return type of method from exported interface has or is using private name 'Vue'.

ERROR in ./props.ts
(45,32): error TS4057: Return type of method from exported interface has or is using private name 'Vue'.

ERROR in ./props.ts
(46,30): error TS4057: Return type of method from exported interface has or is using private name 'Vue'.

ERROR in ./props.ts
(47,33): error TS4057: Return type of method from exported interface has or is using private name 'Vue'.

ERROR in ./props.ts
(48,41): error TS4057: Return type of method from exported interface has or is using private name 'Vue'.

ERROR in ./props.ts
(49,17): error TS4057: Return type of method from exported interface has or is using private name 'Vue'.

ERROR in ./props.ts
(50,18): error TS4057: Return type of method from exported interface has or is using private name 'Vue'.

ERROR in ./props.ts
(51,21): error TS4057: Return type of method from exported interface has or is using private name 'Vue'.

ERROR in ./props.ts
(70,30): error TS4057: Return type of method from exported interface has or is using private name 'Vue'.

ERROR in ./props.ts
(71,18): error TS4057: Return type of method from exported interface has or is using private name 'Vue'.

ERROR in ./props.ts
(72,38): error TS4057: Return type of method from exported interface has or is using private name 'Vue'.

ERROR in ./index.ts
(16,22): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./index.ts
(30,54): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./index.ts
(34,47): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./index.ts
(39,22): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./index.ts
(39,73): error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.

ERROR in ./index.ts
(16,22): error TS4081: Exported type alias 'PropsDefinition' has or is using private name 'Vue'.

ERROR in ./index.ts
(30,54): error TS4081: Exported type alias 'ComponentOptions' has or is using private name 'Vue'.

ERROR in ./index.ts
(34,47): error TS4022: 'extends' clause of exported interface 'RenderContext' has or is using private name 'Vue'.

ERROR in ./index.ts
(39,22): error TS4067: Parameter 'h' of call signature from exported interface has or is using private name 'Vue'.

ERROR in ./index.ts
(39,73): error TS4047: Return type of call signature from exported interface has or is using private name 'Vue'.
error Command failed with exit code 2.`

**Comment by wonderful-panda** [comment]
vue-typed-component 0.7.0 does not support vue 2.5.
If you use vue 2.5, pleasse try 0.8.0.

**Comment by eshimischi** [comment]
@wonderful-panda thanks for fast response, now all is good!
